name: CI/CD - Demo Blue-Green Deploy

on:
  push:
    branches: [main]  
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Checkout 
      - name: Checkout repository
        uses: actions/checkout@v3

      #  Log in Docker Hub 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #  Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flaskapi-app:v2 .
          docker push ${{ secrets.DOCKER_USERNAME }}/flaskapi-app:v2
      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Terraform Init & Apply
      #- name: Terraform Apply
      #  run: |
      #    cd terraform
      #    terraform init
      #    terraform apply -auto-approve

      # 7. Run Blue â†’ Green Playbook
      
      - name: Set up Python & pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install Ansible & k8s deps
        run: |
          pip install ansible kubernetes openshift

      - name: Prepare kubeconfig
        run: |
          mkdir -p $HOME/.kube
          cp /home/ben/.kube/config $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        env:
          HOME: /home/runner

      - name: Test kubectl connectivity
        run: kubectl get ns

      - name: Blue to Green Deploy
        run: |
          ansible-playbook ansible/deploy-bluegreen.yml
        env:
          KUBECONFIG: $HOME/.kube/config
