name: CI/CD - Demo Blue-Green Deploy

on:
  push:
    branches: [main]  
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Checkout 
      - name: Checkout repository
        uses: actions/checkout@v3

      #  Log in Docker Hub 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #  Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flaskapi-app:v2 .
          docker push ${{ secrets.DOCKER_USERNAME }}/flaskapi-app:v2
      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: test ping 
        run: |
          ip a
          curl -k http://127.0.0.1:8001/version
      # Terraform Init & Apply
      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_kubeconfig_raw: ${{ secrets.KUBECONFIG_RAW }}
      # 7. Run Blue â†’ Green Playbook
      - name: Blue to Green Deploy
        run: |
          ansible-playbook ansible/deploy-bluegreen.yml
