name: CI - Build Flask Docker Image

on:
  push:
    branches: [main]  
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Checkout 
      - name: Checkout repository
        uses: actions/checkout@v3

      #  Log in Docker Hub 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #  Build Docker image
      - name: Build Docker image
        run: |
          docker build -t DOCKER_USERNAME/flaskapi-app:v2 .

      #  list Docker image
      - name: List Docker images
        run: docker images
      
      - name: Push Docker image
        run: |
          docker push DOCKER_USERNAME/flaskapi-app:v2
